# Build settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENCE.txt', 'CNAME']


# Site settings
title: GDG DevFest Omsk 2014
email: team@gdg-devfest-omsk.org
description: "GDG DevFest is a set of events all around the world"
baseurl: "/devfest-site"
url: "http://gdg-devfest-omsk.org"
permalink: /blog/:title
googleAnalyticsTrackingId: "UA-23085453-4"
googleAnalyticsSiteUrl: "gdg-devfest-omsk.org"

# Location block
eventLocationName: "Omsk State University"
eventLocationAddress: "55a Mira St, Omsk"
eventStartTime: "2014-11-01T10:00"
eventStartTimeHumanReadable: "Nov 1, 10:00"
eventEndTime: "2014-11-02T16:00"
eventEndTimeHumanReadable: "Nov 2, 16:00"
eventPlaceCoordinates: "55.028372,73.261915"
mapCenterCoordinates: "55.028372,73.26"
mapMobileCenterCoordinates: "55.028372,73.261915"

# Logistics Location Block
logisticsMapCenterCoordinates: "55.028372,73.261915"
logisticsMapMobileCenterCoordinates: "55.028372,73.261915"

#Tweets feed
twitterHashTag: "devfest"
twitterFeed: "fixme" #"http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=900"

# Subscribe

subscribeAction: "http://gdgomsk.us3.list-manage.com/subscribe/post?u=b7e6f7d6f22470e13c0445d05&amp;id=4188aaa7f7" 
#bug "http://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"

# Documents
c4pUrl: "http://short.gdgomsk.org/devfest14-c4p" #"http://bit.ly/dfua-c4p"
c4sponsorsUrl: "mailto:team@gdg-devfest-omsk.org" #"/assets/GDG_DevFest_Partnership.pdf"

# Head
metaKeywords: "event, gdg, devfest, google, programming, android, chrome, developers, omsk"
twitterAccount: "@DevFest"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Header
eventDate: "Join Global DevFest Season! Omsk, November 1-2, 2014."
typeoutTextValues: '"Bay Area", "London", "Омск", "東京", "Львів", "Milano", "Arequipa", "नई दिल्ली", "Bassam", "Madrid", "..."'

# About Event Block
eventName: "GDG DevFest Omsk 2014"

# Team Block
aboutUs: Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences. #fixme change text

# Speakers List Block
showSessions: true
thumbnailsFolder: /img/speakers/

# Footer
gplusFollowUsUrl: "http://plus.google.com/102520175692033125056"
twitterFollowUsUrl: "http://twitter.com/intent/user?screen_name=GDGOmsk"
vkFollowUsUrl: "http://vk.com/gdgomsk_news"

# Blog
blogCommentsEnabled: false
discusShortName: "fixme" #"devfestua"
