# Build Settings
markdown: kramdown
permalink: pretty
exclude:
  - '/automation/'
  - 'README.md'
  - 'LICENSE.txt'
  - 'CNAME'
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'Rakefile'


# Site Settings
title: GDG DevFest Omsk 2014
email: team@gdg-devfest-omsk.org
description: "GDG DevFest is a set of events all around the world"
baseurl: ""
url: "http://www.gdg-devfest-omsk.org"
permalink: /blog/:title
googleAnalyticsTrackingId: "UA-23085453-4"
googleAnalyticsSiteUrl: "gdg-devfest-omsk.org"
siteVerification: "" # TODO: Get google site verification code

# Organizer Info
organizerName: "GDG Omsk"
organizerAlternateName: "Google Developer Group Omsk"
organizerDescription: "Open and volunteer geek communities who create exciting projects and share experience about Google technology with passion."
organizerEmail: "team@gdg-devfest-omsk.org"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://gdgomsk.org/"

# Location block
locationBlockTitle: "Location"
eventLocationLink: "http://imit.omsu.ru" # FIXME: set event location link
eventLocationName: "IMIT, OmSU"
eventStreetAddress: "55a Mira St"
eventAddressLocality: "Omsk, Russia"
eventPlaceCoordinates: "55.028372, 73.261915"
mapCenterCoordinates: "55.028372, 73.26"
mapMobileCenterCoordinates: "55.028372, 73.261915"
eventAddressLocalityRegion: "Omskaya Oblast'"
eventPostalCode: "644077"
eventAddressCountry: "Russia"
eventStartTime: "2014-12-13T13:30"
eventDoorTime: "09:00"
eventEndTime: "2014-12-14T20:00"
eventStartTimeHumanReadable: "Dec 13, 13:30"
eventEndTimeHumanReadable: "Dec 14, 20:00"

# Subscribe

subscribeAction: "http://gdgomsk.us3.list-manage.com/subscribe/post?u=b7e6f7d6f22470e13c0445d05&amp;id=4188aaa7f7"
#bug "http://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"

# Documents
c4pUrl: "http://short.gdgomsk.org/devfest14-c4p" #"http://bit.ly/dfua-c4p"
c4partnersUrl: "mailto:team@gdg-devfest-omsk.org" #"/assets/GDG_DevFest_Partnership.pdf"

# Head
metaKeywords: "event, gdg, devfest, google, programming, android, chrome, developers, omsk"
twitterAccount: "@DevFest"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# About Event Block
eventName: "GDG DevFest Omsk 2014"

# Documents
c4sponsorsUrl: "mailto:team@gdg-devfest-omsk.org"

# Navigation
navigationLinks:
 - {permalink: "/", text: "About"}
 - {permalink: "/rules/", text: "Rules"}
 - {permalink: "/schedule/", text: "Schedule"}
# - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/location/", text: "Location"}
 - {permalink: "/organizers/", text: "Organizers"}
bottomNavigationLinks:
 - {link: "http://gdg-omsk.timepad.ru/event/160828/", text: "I want to take part"}
rightNavigationButtons:
 - {link: "http://gdg-omsk.timepad.ru/event/160828/", text: "I want to take part"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "GDG DevFest <typeout> 2014"
eventDate: "Join Global DevFest Season! Omsk, December 13-14, 2014."
typeoutTextValues: '"Омск", "Bay Area", "London", "東京", "Львів", "Milano", "Arequipa", "नई दिल्ली", "Bassam", "Madrid", "..."'
typeoutFallback: "Omsk"
heroButtons:
 - {link: "http://gdg-omsk.timepad.ru/event/160828/", text: "I want to take part"}

# About Block
aboutTitle: "About GDG DevFest 2014"
aboutBlock:
 - {title: "Seminar", image: "class.jpg", text: "Learn before Hackathon<br/>December 13" }
 - {title: "Hackathon", image: "hackathon-6.jpg", text: "Make your own app on full-day Hackathon!<br/>December 14" }
 - {title: "Hackfair", image: "hackfair.jpg", text: "Share your results and win great prizes!<br/>Main part of Hackathon" }

# Statistic Block
statisticBlockImage: "cover.jpg"
statisticBlock:
 - {count: "2", specialCharacter: "", info: "Days", detail: "Saturday & Sunday"}
 - {count: "3", specialCharacter: "", info: "Tracks", detail: "Mobile, Web & AR/VR"}
 - {count: "80", specialCharacter: "", info: "Attendees", detail: "Heroes of Keyboard & Mouse"}
 - {count: "960", specialCharacter: "+", info: "Mins", detail: "Epic & Unique Gameplay"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Rockstar speakers"
rockstarSpeakersButtonText: "See all speakers"

# Venue Block
venueBlockTitle: "Welcome to University"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Omsk State University"
venueFeatures: ["<b>Institute of Mathematics and Information Technologies</b> — power of education and comfortable lecture rooms."]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "#devfest #omsk"
twitterHashTagQuery: "%23devfest%23omsk"
twitterFeed: "" # http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=900

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a partner"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe to news and invites"
subscribeAction: "http://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registration will be open around end of September. Number of tickets are very limited.<br/>Dates of event is subject of change. Stay tuned!"

# Tickets Block
ticketsTitle: "Pricetable"
ticketsInfo: "Tickets grant access to all conference sections, coffee brakes, lunch and party. Accommodation is NOT included in the ticket price."
ticketsOffers:
 -
  name: "Invites"
  price: "Free"
  priceCurrency: ""
  ticketsNumber: "20"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Sent Out"
  ticketContentList: [""]
  validFrom: "2014-08-25T10:00"
  validThrough: "2014-11-22T00:00"
  disabled: false
 -
  name: "Tickets"
  price: "Free"
  priceCurrency: ""
  ticketsNumber: "100"
  featured: true
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Get now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-11-22T10:00"
  validThrough: "2014-12-12T23:59"
  disabled: true

# Footer
socialLinks:
 - {link: "http://plus.google.com/102520175692033125056", icon: "google-plus"}
 - {link: "http://twitter.com/intent/user?screen_name=GDGOmsk", icon: "twitter"}
 - {link: "http://vk.com/gdgomsk_news", icon: "vk"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://www.gdgomsk.org", text: "GDG Omsk"}
   - {link: "https://developers.google.com", text: "Google Developers"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:team@gdg-devfest-omsk.org", text: "team@gdg-devfest-omsk.org"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}
   - {link: "https://github.com/GDGOmsk/devfest-site/issues/new", text: "Caught a bug?"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: false
discusShortName: "fixme" # "devfestua"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "We're small team of enthusiasts. We like knowledges, communication and rocket-science technologies. We're are organizing GDG DevFest Omsk to inspire you to make positive step forward. We'll do our best to create magic, productive and smiling atmosphere on the event. We hope, DevFest Omsk will light new talents and new awesome initiatives!"

# Logistics Find Way Block
findWayTitle: "Omsk, Mira 55a"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "55.028372, 73.261915"
logisticsMapMobileCenterCoordinates: "55.028372, 73.261915"

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Omsk"
directionDetailsCards:
 - {title: "From other City", information: 'You can arrive by plane or by train. Both airport and railway station are inside the city border. So venue is easily reachable by car, public transport or taxi.'}
 - {title: "Public Transit", information: 'Google Transit is available in Omsk. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Omsk.'}
 - {title: "Hotels", information: 'Omsk has lots of great hotels and hostels. You will surely find the one that will suit you.'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "http://www.hotel-mayak.ru/", text: "Mayak Hotel"}
     - {link: "http://razumovsky-hotel.com/", text: "Razumovsky Business Club Hotel"}
     - {link: "http://likehostels.ru/omsk/", text: "Like Hostel"}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: true

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
 - {title: "Wearable Devices", image: "wearables.png", details: "A wearable computer is an electronic device capable of storing and processing data that is incorporated into a person's clothing or personal accessories. Famous examples of wearable devices in our days are Google Glass, Moto X 360, Pebble, Apple iWatch and a lot of other devices. Wearable computing is huge and rapidly growing area, it provides a lot of opportunities for innovations and creation of new great products and solutions! Don't skip a chance to create you one at hackathon!"}
 - {title: "Modern Front-end", image: "front-end.png", details: "In last years it was a incredible spurt in innovation that completely changes what it means to be a web front-end developer! It's moment of renaissance and right time for creation of really awesome apps with great user experience. The main problem is to know right tools and techs! Hackathon is perfect place for deep dive into such things like Web Components, Polymer, AngularJS, Dart, БЭМ, Bootstrap, Bower, GruntJS, NPM, JSHint and others. Also DevFest is great place for sharing of knowledge and open discussions."}
 - {title: "AR/VR Reality", image: "cardboard.png", details: "With Augmented Reality apps, users are able to interact with virtual contents in the real world, and are able to distinguish between the two. Virtual reality is all about the creation of a virtual world, for example for walking in Hermitage museum or playing immersive game. With Nexus 5 and piece of cardboard almost everyone can create great AR or VR app! If you have cool ideas of AR/VR apps and you love Maths, we would be happy to see your application! "}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"

sass:
  sass_dir: _sass
  style: :compressed
